### ISSUE TITLE
跑不起来哦

### ISSUE THREAD

**Issue by Shimingli** [G-Joker/WeaponApp#2]
然后又不报错，是不是我的打开方式不对

**Comment by useataaaaa** [comment]
1.使用真机进行调试
2.目前我们还在开发阶段，可以先运行 "app.mine"、"app.message"模块

在这里选择module切换
![wx20170925-105857](https://user-images.githubusercontent.com/9319738/30790779-a9ec7672-a173-11e7-8c01-3ac6653aa097.png)

**Comment by WeaponZhi** [comment]
现在我们还在开发阶段，具体宿主跑起来需要输入以下指令，不过是能跑起来的，需要输入以下指令：
gradlew cleanLib
gradlew buildLib
gradlew cleanBundle
gradlew buildBundle
具体请参考 small 打包教程，我们也会在后续写一个具体doc的

**Comment by Shimingli** [comment]
tks! 哇  就要这样  才能 跑起来    谢谢，万分感谢  ！！

**Comment by Shimingli** [comment]
![image](https://user-images.githubusercontent.com/20720544/30796512-f5a27a62-a204-11e7-9d0e-d57c619082c5.png)
我在提个问题，这是在跑app_main 的时候包的错，然后我把极光的sdk加到这里来，然后才可以跑起来，所以确定下  是不是依赖加少了 
![Uploading image.png…]()

**Comment by Shimingli** [comment]
![image](https://user-images.githubusercontent.com/20720544/30796627-7c28525a-a205-11e7-819a-087fbc6aff5c.png)

**Comment by WeaponZhi** [comment]
@xiaweizi

**Comment by xiaweizi** [comment]
@Shimingli 
目前是把一些极光的库放到了**宿主**中(考虑到在 `Application`下，极光的初始化)，而把自定义的 `MyReceiver`放在了`app.main`下(接收到推送，方便实现自定义的跳转)。所以单独跑`app.main`的时候，会出现`lib`的丢失，但是整个项目跑起来的是没问题的，后面会对其进一步的优化~

**Comment by Shimingli** [comment]
tks！谢谢

**Comment by xiaweizi** [comment]
@Shimingli 
客气了~
