### ISSUE TITLE
大佬，你好

### ISSUE THREAD

**Issue by cjcj125125** [G-Joker/WeaponApp#4]
在code小生的公众号上看到您的这个small插件化，对此很感兴趣，但是不知道从何入手，看了几个文档也不是基础的，希望您可以指点，谢谢，另外，你的项目跑起来了，看了下比较吃力，所以运行起来一点就挂了，也不知道怎么改，希望大佬赐教，万分感谢

**Comment by useataaaaa** [comment]
请提供对应设备以及Log的信息，帮助我们排查，可先参考 [#2](https://github.com/G-Joker/WeaponApp/issues/2)
