### ISSUE TITLE
服务器端可以运行起来

### ISSUE THREAD

**Issue by cjcj125125** [G-Joker/WeaponApp#5]
服务器端可以运行起来，但是输入localhost:8080/home....无法打开网页，求解，我把放到服务器上，安装了tomcat也是一样的，不行

**Comment by useataaaaa** [comment]
请先参考 ：[Android程序员搭建一个属于自己的服务器，不再求各种公共API](http://www.jianshu.com/p/4a0d40806ea2) 这篇文章，查看是否有步骤遗漏。

**Comment by foxleezh** [comment]
@cjcj125125 有按照教程一步步做吗？PC是windows还是mac，tomcat版本是多少
