### ISSUE TITLE
 idea引入工程后报错

### ISSUE THREAD

**Issue by marren06** [G-Joker/WeaponApp#6]
![tim 20171031170506](https://user-images.githubusercontent.com/17778482/32215986-9edfef0e-be5e-11e7-9e0f-45bed86cea26.png)
 对你的这个项目很有兴趣，现在我idea导入server端后报错不知道什么原因！如上图   请指点下 谢谢

**Comment by foxleezh** [comment]
@xuekaiqi  请问你导入项目时是选择的Gradle吗？我刚刚重新拉了项目，然后选择Gradle没有问题

![](https://user-images.githubusercontent.com/7986735/32221179-8349cff6-be6f-11e7-83b4-c2916a272d99.png)

![](https://user-images.githubusercontent.com/7986735/32221249-c46cd37a-be6f-11e7-8611-2dc2708e9a18.png)

**Comment by marren06** [comment]
@foxleezh 就是这个原因！谢谢了 ！运行起来了！ 我也是看着你的项目刚跟着学 ~_~
