### ISSUE TITLE
大佬，启动报错

### ISSUE THREAD

**Issue by yingchen066** [G-Joker/WeaponApp#7]
Execution failed for task ':lib.middleware:processReleaseResources'.
> In strict mode, we do not allow vendor aars, please declare them in host build.gradle:
      - compile('com.android.support:design:26.1.0')
      - compile('com.android.support:appcompat-v7:26.1.0')
  or turn off the strict mode in root build.gradle:
      small {
          strictSplitResources = false
      }

必须要关掉严格模式吗

**Comment by WeaponZhi** [comment]
要加的，因为个别 Library 引用了 aar，你试试加了后能不能编译通过

**Comment by yingchen066** [comment]
改了之后可以编译通过，但是运行app之后报Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.的错误，能否把你的工作副本发一份到849119257@qq.com

**Comment by WeaponZhi** [comment]
@yingchen066 我晚些时候去看一下，可能最近开发合并出问题了，谢谢提出问题，好了我会反馈给你

**Comment by xiaweizi** [comment]
@yingchen066 您是最新代码吗？有没有修改过源码，比如自己添加了依赖？
