### ISSUE TITLE
导入工程无法运行，提示“错误: 找不到或无法加载主类 com.app.server.BaseApplication”

### ISSUE THREAD

**Issue by qinkaituhu** [G-Joker/WeaponApp#9]
错误: 找不到或无法加载主类 com.app.server.BaseApplication

Process finished with exit code 1

请问如何导入的？新手

**Comment by WeaponZhi** [comment]
加QQ群交流 559169318

**Comment by foxleezh** [comment]
@qinkaituhu 最新教程已更新，在导入项目时选择gradle可解决
